DELETE FROM plugin WHERE id = '90016';
DELETE FROM plugin_sid where plugin_id = '90016';
INSERT IGNORE INTO software_cpe VALUES ('cpe:/h:APC-UPS:APC-UPS:-', 'APC-UPS', '1.0' , 'APC-UPS APC-UPS 1.0', 'APC-UPS', 'APC-UPS:90016');
INSERT IGNORE INTO plugin (id, type, name, description,product_type,vendor) VALUES (90016, 1, 'APC-UPS', 'APC UPS',17,'AlienVault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 1, 3, 5, 'APC: Coldstart');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2, 3, 5, 'APC: Warmstart');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 3, 3, 3, 'APC: SNMP configuration change');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 7, 3, 1, 'APC: Network service started');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 8, 3, 3, 'APC: Password changed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 12, 3, 1, 'APC: File transfer started');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 13, 3, 1, 'APC: File transfer started');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 15, 3, 1, 'APC: File transfer failed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 20, 3, 1, 'APC: Console user logged in');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 21, 3, 1, 'APC: Web user logged in');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 22, 3, 1, 'APC: FTP user logged in');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 30, 3, 1, 'APC: Console user logged out');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 31, 3, 1, 'APC: Web user logged out');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 32, 3, 1, 'APC: FTP user logged out');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 24, 3, 1, 'APC: Reset to defaults');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 25, 3, 1, 'APC: Initializing data in the file');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 26, 3, 1, 'APC: Email information');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 36, 3, 1, 'APC: Trace information');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 37, 3, 3, 'APC: Modem dial-out failed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 38, 3, 1, 'APC: RMS CLI user logged in');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 39, 3, 1, 'APC: RMS CLI user logged out');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 42, 3, 1, 'APC: Network service information');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 43, 3, 1, 'APC: Network service could not start');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 44, 3, 1, 'APC: Network service stopped');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 257, 3, 1, 'APC: Communications established');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 258, 3, 5, 'APC: Communications lost');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 259, 3, 5, 'APC: Sensed a load greater than 100 percent of rated capacity');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 260, 3, 1, 'APC: Overload condition cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 261, 3, 1, 'APC: Passed internal self-test');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 262, 3, 5, 'APC: Failed internal diagnostic self-test');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 263, 3, 5, 'APC: Batteries discharged');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 264, 3, 1, 'APC: Battery discharge condition cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 265, 3, 3, 'APC: Switched to battery backup power');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 266, 3, 1, 'APC: Returned from battery backup power');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 267, 3, 3, 'APC: Enabled SmartBoost; low incoming line voltage');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 268, 3, 1, 'APC: Returned from SmartBoost');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 269, 3, 3, 'APC: Enabled SmartTrim; high incoming line voltage');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 270, 3, 1, 'APC: Returned from SmartTrim');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 271, 3, 5, 'APC: Battery power is low and will soon be exhausted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 272, 3, 1, 'APC: Returned from a Low-Battery condition');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 275, 3, 1, 'APC: Turned on');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 276, 3, 3, 'APC: Turned off');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 277, 3, 3, 'APC: Entered sleep mode');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 278, 3, 1, 'APC: Returned from sleep mode');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 279, 3, 3, 'APC: Started reboot sequence');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 281, 3, 5, 'APC: Batteries need immediate replacement');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 282, 3, 1, 'APC: Bad battery condition cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 283, 3, 5, 'APC: In bypass due to an internal fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 284, 3, 3, 'APC: In bypass due to user command via software or panel');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 285, 3, 3, 'APC: In bypass initiated by user');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 286, 3, 1, 'APC: Returned from bypass');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 287, 3, 5, 'APC: Base module bypass power supply failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 289, 3, 1, 'APC: External battery pack communications established');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 290, 3, 5, 'APC: External battery pack communications lost');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 291, 3, 1, 'APC: Battery calibration test initiated');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 292, 3, 1, 'APC: Battery calibration complete');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 293, 3, 1, 'APC: Graceful shutdown in progress');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 294, 3, 3, 'APC: SmartBoost or SmartTrim relay failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 295, 3, 1, 'APC: SmartBoost or SmartTrim relay failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 296, 3, 3, 'APC: Bad output voltage condition');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 297, 3, 1, 'APC: Bad output voltage condition cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 298, 3, 3, 'APC: Battery charger failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 299, 3, 1, 'APC: Battery charger failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 300, 3, 3, 'APC: Internal battery temperature threshold violation');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 301, 3, 1, 'APC: Internal battery temperature threshold violation cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 303, 3, 3, 'APC: No batteries installed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 304, 3, 1, 'APC: No batteries installed cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 305, 3, 3, 'APC: Scheduled shutdown initiated');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 306, 3, 1, 'APC: Scheduled shutdown failed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 307, 3, 5, 'APC: Scheduled shutdown deleted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 513, 3, 5, 'APC: Power Module failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 514, 3, 1, 'APC: Power Module failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 515, 3, 5, 'APC: Intelligence Module failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 516, 3, 1, 'APC: Intelligence Module failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 517, 3, 5, 'APC: Redundant Intelligence Module failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 518, 3, 1, 'APC: Redundant Intelligence Module failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 519, 3, 5, 'APC: Battery failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 520, 3, 1, 'APC: Battery failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 521, 3, 5, 'APC: Load(kVA) alarm threshold violation');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 522, 3, 1, 'APC: Load(kVA) alarm threshold violation cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 523, 3, 5, 'APC: Redundancy lost');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 524, 3, 1, 'APC: Redundancy returned');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 525, 3, 5, 'APC: Redundancy below alarm threshold');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 526, 3, 1, 'APC: Redundancy below alarm threshold cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 527, 3, 5, 'APC: Bypass not in range; either frequency or voltage');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 528, 3, 1, 'APC: Bypass not in range; either frequency or voltage');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 529, 3, 5, 'APC: Bypass contactor stuck in bypass position');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 530, 3, 1, 'APC: Bypass contactor stuck in bypass position cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 531, 3, 5, 'APC: Bypass contactor stuck in on-line position');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 532, 3, 1, 'APC: Bypass contactor stuck in on-line position cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 533, 3, 5, 'APC: In bypass due to an internal fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 534, 3, 1, 'APC: In bypass due to an internal fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 535, 3, 5, 'APC: In bypass due to an overload');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 536, 3, 1, 'APC: In bypass due to an overload cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 537, 3, 5, 'APC: In maintenance bypass');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 538, 3, 1, 'APC: In maintenance bypass cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 539, 3, 5, 'APC: Input circuit breaker tripped open');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 540, 3, 1, 'APC: Input circuit breaker tripped open cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 541, 3, 5, 'APC: System level fan failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 542, 3, 1, 'APC: System level fan failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 543, 3, 5, 'APC: Redundant Intelligence Module in control');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 544, 3, 1, 'APC: Redundant Intelligence Module in control cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 545, 3, 5, 'APC: IIC inter-module communications failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 546, 3, 1, 'APC: IIC inter-module communications failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 547, 3, 5, 'APC: No working Power Modules');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 548, 3, 1, 'APC: No working Power Modules cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 551, 3, 5, 'APC: Runtime below alarm threshold');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 552, 3, 1, 'APC: Runtime below alarm threshold cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 553, 3, 5, 'APC: Extended Run Frame fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 554, 3, 1, 'APC: Extended Run Frame fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 555, 3, 5, 'APC: Output voltage out of range');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 556, 3, 1, 'APC: Output voltage out of range cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 557, 3, 5, 'APC: Not synchronized fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 558, 3, 1, 'APC: Not synchronized fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 559, 3, 5, 'APC: No batteries installed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 560, 3, 1, 'APC: No batteries installed cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 561, 3, 5, 'APC: Battery voltage high');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 562, 3, 1, 'APC: Battery voltage high cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 563, 3, 5, 'APC: Non-specific fault; Access UPS keyboard for details');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 564, 3, 1, 'APC: Non-specific fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 565, 3, 5, 'APC: Site wiring fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 566, 3, 1, 'APC: Site wiring fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 567, 3, 5, 'APC: Backfeed protection relay open');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 568, 3, 1, 'APC: Backfeed protection relay open cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 569, 3, 5, 'APC: Bit 28 of the abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 570, 3, 1, 'APC: Bit 28 of the abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 571, 3, 5, 'APC: Bit 29 of the abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 572, 3, 1, 'APC: Bit 29 of the abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 573, 3, 5, 'APC: Bit 30 of the abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 574, 3, 1, 'APC: Bit 30 of the abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 575, 3, 5, 'APC: Bit 31 of the abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 576, 3, 1, 'APC: Bit 31 of the abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 577, 3, 1, 'APC: Number of batteries increased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 578, 3, 1, 'APC: Number of batteries decreased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 579, 3, 1, 'APC: Number of Power Modules increased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 580, 3, 1, 'APC: Number of Power Modules increased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 581, 3, 1, 'APC: Intelligence Module inserted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 582, 3, 1, 'APC: Intelligence Module removed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 583, 3, 1, 'APC: Redundant Intelligence Module inserted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 584, 3, 1, 'APC: Redundant Intelligence Module removed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 585, 3, 1, 'APC: Number of Extended Run Frames increased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 586, 3, 1, 'APC: Number of Extended Run Frames decreased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 587, 3, 1, 'APC: Number of System Power Supplies increased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 588, 3, 1, 'APC: Number of System Power Supplies decreased');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 589, 3, 1, 'APC: External Switch Gear Q001 closed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 590, 3, 1, 'APC: External Switch Gear Q001 opened');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 591, 3, 1, 'APC: External Switch Gear Q002 closed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 592, 3, 1, 'APC: External Switch Gear Q002 opened');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 593, 3, 1, 'APC: External Switch Gear Q003 closed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 594, 3, 1, 'APC: External Switch Gear Q003 opened');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 595, 3, 1, 'APC: External Switch Gear Q004 closed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 596, 3, 1, 'APC: External Switch Gear Q004 opened');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2561, 3, 5, 'APC: External Switch Gear failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2562, 3, 1, 'APC: External Switch Gear failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2563, 3, 5, 'APC: External Transformer over temperature');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2564, 3, 1, 'APC: External Transformer over temperature cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2565, 3, 5, 'APC: External DC Circuit Breaker tripped');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2566, 3, 1, 'APC: External DC Circuit Breaker closed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2567, 3, 5, 'APC: System Power Supply failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2568, 3, 1, 'APC: System Power Supply failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2569, 3, 5, 'APC: Battery Monitor Card failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2570, 3, 1, 'APC: Battery Monitor Card failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2571, 3, 5, 'APC: Battery Monitor Card removed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2572, 3, 1, 'APC: Battery Monitor Card inserted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2573, 3, 5, 'APC: XR Communication Card failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2574, 3, 1, 'APC: XR Communication Card failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2575, 3, 5, 'APC: XR Communication Card removed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2576, 3, 1, 'APC: XR Communication Card inserted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2577, 3, 5, 'APC: External Switch Gear Monitoring Card failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2578, 3, 1, 'APC: External Switch Gear Monitoring Card failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2579, 3, 5, 'APC: External Switch Gear Monitoring Card removed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2580, 3, 1, 'APC: External Switch Gear Monitoring Card inserted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2581, 3, 5, 'APC: Internal DC Circuit Breaker tripped');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2582, 3, 1, 'APC: Internal DC Circuit Breaker closed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2583, 3, 5, 'APC: Static Bypass Switch failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2584, 3, 1, 'APC: Static Bypass Switch failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2585, 3, 5, 'APC: System EEProm removed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2586, 3, 1, 'APC: System EEProm inserted');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2587, 3, 5, 'APC: System EEProm failure');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2588, 3, 1, 'APC: System EEProm failure cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2589, 3, 5, 'APC: UPS is in forced bypassed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2590, 3, 1, 'APC: UPS returned from forced bypassed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2591, 3, 5, 'APC: Bit 15 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2592, 3, 1, 'APC: Bit 15 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2593, 3, 5, 'APC: Bit 16 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2594, 3, 1, 'APC: Bit 16 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2595, 3, 5, 'APC: Bit 17 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2596, 3, 1, 'APC: Bit 17 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2597, 3, 5, 'APC: Bit 18 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2598, 3, 1, 'APC: Bit 18 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2599, 3, 5, 'APC: Bit 19 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2600, 3, 1, 'APC: Bit 19 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2601, 3, 5, 'APC: Bit 20 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2602, 3, 1, 'APC: Bit 20 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2603, 3, 5, 'APC: Bit 21 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2604, 3, 1, 'APC: Bit 21 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2605, 3, 5, 'APC: Bit 22 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2606, 3, 1, 'APC: Bit 22 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2607, 3, 5, 'APC: Bit 23 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2608, 3, 1, 'APC: Bit 23 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2609, 3, 5, 'APC: Bit 24 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2610, 3, 1, 'APC: Bit 24 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2611, 3, 5, 'APC: Bit 25 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2612, 3, 1, 'APC: Bit 25 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2613, 3, 5, 'APC: Bit 26 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2614, 3, 1, 'APC: Bit 26 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2615, 3, 5, 'APC: Bit 27 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2616, 3, 1, 'APC: Bit 27 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2617, 3, 5, 'APC: Bit 28 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2618, 3, 1, 'APC: Bit 28 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2619, 3, 5, 'APC: Bit 29 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2620, 3, 1, 'APC: Bit 29 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2621, 3, 5, 'APC: Bit 30 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2622, 3, 1, 'APC: Bit 30 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2623, 3, 5, 'APC: Bit 31 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2624, 3, 1, 'APC: Bit 31 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2625, 3, 5, 'APC: Bit 32 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2626, 3, 1, 'APC: Bit 32 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2627, 3, 5, 'APC: Bit 33 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2628, 3, 1, 'APC: Bit 33 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2629, 3, 5, 'APC: Bit 34 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2630, 3, 1, 'APC: Bit 34 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2631, 3, 5, 'APC: Bit 35 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2632, 3, 1, 'APC: Bit 35 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2633, 3, 5, 'APC: Bit 36 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2634, 3, 1, 'APC: Bit 36 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2635, 3, 5, 'APC: Bit 37 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2636, 3, 1, 'APC: Bit 37 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2637, 3, 5, 'APC: Bit 38 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2638, 3, 1, 'APC: Bit 38 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2639, 3, 5, 'APC: Bit 39 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2640, 3, 1, 'APC: Bit 39 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2641, 3, 5, 'APC: Bit 40 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2642, 3, 1, 'APC: Bit 40 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2643, 3, 5, 'APC: Bit 41 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2644, 3, 1, 'APC: Bit 41 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2645, 3, 5, 'APC: Bit 42 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2646, 3, 1, 'APC: Bit 42 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2647, 3, 5, 'APC: Bit 43 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2648, 3, 1, 'APC: Bit 43 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2649, 3, 5, 'APC: Bit 44 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2650, 3, 1, 'APC: Bit 44 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2651, 3, 5, 'APC: Bit 45 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2652, 3, 1, 'APC: Bit 45 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2653, 3, 5, 'APC: Bit 46 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2654, 3, 1, 'APC: Bit 46 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2655, 3, 5, 'APC: Bit 47 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2656, 3, 1, 'APC: Bit 47 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2657, 3, 5, 'APC: Bit 48 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2658, 3, 1, 'APC: Bit 48 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2659, 3, 5, 'APC: Bit 49 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2660, 3, 1, 'APC: Bit 49 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2661, 3, 5, 'APC: Bit 50 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2662, 3, 1, 'APC: Bit 50 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2663, 3, 5, 'APC: Bit 51 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2664, 3, 1, 'APC: Bit 51 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2665, 3, 5, 'APC: Bit 52 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2666, 3, 1, 'APC: Bit 52 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2667, 3, 5, 'APC: Bit 53 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2668, 3, 1, 'APC: Bit 53 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2669, 3, 5, 'APC: Bit 54 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2670, 3, 1, 'APC: Bit 54 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2671, 3, 5, 'APC: Bit 55 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2672, 3, 1, 'APC: Bit 55 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2673, 3, 5, 'APC: Bit 56 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2674, 3, 1, 'APC: Bit 56 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2675, 3, 5, 'APC: Bit 57 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2676, 3, 1, 'APC: Bit 57 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2677, 3, 5, 'APC: Bit 58 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2678, 3, 1, 'APC: Bit 58 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2679, 3, 5, 'APC: Bit 59 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2680, 3, 1, 'APC: Bit 59 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2681, 3, 5, 'APC: Bit 60 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2682, 3, 1, 'APC: Bit 60 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2683, 3, 5, 'APC: Bit 61 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2684, 3, 1, 'APC: Bit 61 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2685, 3, 5, 'APC: Bit 62 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2686, 3, 1, 'APC: Bit 62 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2687, 3, 5, 'APC: Bit 63 of the second abnormal condition register set');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 2688, 3, 1, 'APC: Bit 63 of the second abnormal condition register cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 769, 3, 5, 'APC: Contact 1 fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 770, 3, 1, 'APC: Contact 1 fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 771, 3, 5, 'APC: Contact 2 fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 772, 3, 1, 'APC: Contact 2 fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 773, 3, 5, 'APC: Contact 3 fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 774, 3, 1, 'APC: Contact 3 fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 775, 3, 5, 'APC: Contact 4 fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 776, 3, 1, 'APC: Contact 4 fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 777, 3, 5, 'APC: Low temperature threshold violation on probe 1');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 778, 3, 1, 'APC: Low temperature threshold violation on probe 1 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 779, 3, 5, 'APC: High temperature threshold violation on probe 1');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 780, 3, 1, 'APC: High temperature threshold violation on probe 1 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 781, 3, 5, 'APC: Low humidity threshold violation on probe 1');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 782, 3, 1, 'APC: Low humidity threshold violation on probe 1 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 783, 3, 5, 'APC: High humidity threshold violation on probe 1');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 784, 3, 1, 'APC: High humidity threshold violation on probe 1 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 785, 3, 5, 'APC: Low temperature threshold violation on probe 2');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 786, 3, 1, 'APC: Low temperature threshold violation on probe 2 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 787, 3, 5, 'APC: High temperature threshold violation on probe 2');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 788, 3, 1, 'APC: High temperature threshold violation on probe 2 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 789, 3, 5, 'APC: Low humidity threshold violation on probe 2');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 790, 3, 1, 'APC: Low humidity threshold violation on probe 2 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 791, 3, 5, 'APC: High humidity threshold violation on probe 2');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 792, 3, 1, 'APC: High humidity threshold violation on probe 2 cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 793, 3, 1, 'APC: Communications established');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 794, 3, 5, 'APC: Communications lost');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 795, 3, 5, 'APC: Integrated contact fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 796, 3, 1, 'APC: Integrated contact fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 797, 3, 5, 'APC: Low temperature threshold violation on integrated probe');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 799, 3, 5, 'APC: High temperature threshold violation on integrated probe');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 801, 3, 5, 'APC: Low humidity threshold violation on integrated probe');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 802, 3, 1, 'APC: Low humidity threshold violation on integrated probe cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 803, 3, 5, 'APC: High humidity threshold violation on integrated probe');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 804, 3, 1, 'APC: High humidity threshold violation on integrated probe cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 805, 3, 3, 'APC: Integrated relay output fault');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 806, 3, 3, 'APC: Integrated relay output fault cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 4, 3, 1, 'APC: Detected an unauthorized user attempting to access the SNMP interface');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 5, 3, 1, 'APC: Detected an unauthorized user attempting to access the Console interface');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 6, 3, 1, 'APC: Detected an unauthorized user attempting to access the Web interface');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 549, 3, 1, 'APC: Load shutdown from bypass; input frequency or voltage outside limits');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 550, 3, 1, 'APC: Load shutdown from bypass cleared; input frequency or voltage outside limits');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 798, 3, 1, 'APC: Low temperature threshold violation on integrated probe cleared');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (90016, 800, 3, 1, 'APC: High temperature threshold violation on integrated probe cleared');
