-- imperva-securesphere
-- plugin_id: 1679

DELETE FROM plugin WHERE id = "1679";
DELETE FROM plugin_sid where plugin_id = "1679";

INSERT IGNORE INTO plugin (id, type, name, description) VALUES (1679, 1, 'imperva-securesphere', 'Imperva SecureSphere');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 100, NULL, NULL, 'Unknown Imperva Message' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 150, NULL, NULL, 'Abnormally Long Header Line' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 151, NULL, NULL, 'Abnormally Long URL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 152, NULL, NULL, 'Access of Administrative Interface' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 153, NULL, NULL, 'Access of Internal Components' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 154, NULL, NULL, 'Attempt to Execute Privileged Operation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 155, NULL, NULL, 'Bad IP Option Length' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 156, NULL, NULL, 'Bad IP Option Padding' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 157, NULL, NULL, 'Bad Total Length of IP Packet' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 158, NULL, NULL, 'Black Listed Table' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 159, NULL, NULL, 'Brute Force' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 160, NULL, NULL, 'Buffer Overflow' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 161, NULL, NULL, 'Card Track Data Detection' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 162, NULL, NULL, 'Cookie Injection' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 163, NULL, NULL, 'Cookie Name Exceeds Allowed Maximum' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 164, NULL, NULL, 'Cookie Poisoning' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 165, NULL, NULL, 'Cookie Tampering' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 166, NULL, NULL, 'Cookie Value Length Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 167, NULL, NULL, 'Cookie Value Untraceable' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 168, NULL, NULL, 'Cross-site Scripting' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 169, NULL, NULL, 'Custom Policy Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 170, NULL, NULL, 'DB Login Statement Error' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 171, NULL, NULL, 'DB Unauthorized Host' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 172, NULL, NULL, 'DB Unauthorized OS User' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 173, NULL, NULL, 'Denial of Service (DoS)' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 174, NULL, NULL, 'Directory Traversal' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 175, NULL, NULL, 'Distributed Denial of Service (DDoS)' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 176, NULL, NULL, 'Double URL Encoding' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 177, NULL, NULL, 'Excessive Failed Login attempts to the DB' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 178, NULL, NULL, 'Extremely Long HTTP Request Alert' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 179, NULL, NULL, 'Extremely Long URL Parameter' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 180, NULL, NULL, 'File/Parameter Enumeration' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 181, NULL, NULL, 'Forceful Browsing' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 182, NULL, NULL, 'Fragmented Packet' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 183, NULL, NULL, 'HTTP Probe Parse Error' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 184, NULL, NULL, 'HTTP Request or Response Parse Error' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 185, NULL, NULL, 'Illegal Byte Code Character in Header Name' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 186, NULL, NULL, 'Illegal Byte Code Character in Parameter Name' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 187, NULL, NULL, 'Illegal Byte Code Character in Request' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 188, NULL, NULL, 'Illegal Byte Code Character in Request Content' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 189, NULL, NULL, 'Illegal Byte Code in Method' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 190, NULL, NULL, 'Illegal Byte Code in Parameter Value' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 191, NULL, NULL, 'Illegal Byte Code in Query String' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 192, NULL, NULL, 'Illegal Byte Code in URL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 193, NULL, NULL, 'Illegal Chunk Size' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 194, NULL, NULL, 'Illegal Content Type' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 195, NULL, NULL, 'Illegal Host Name' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 196, NULL, NULL, 'Illegal HTTP Version' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 197, NULL, NULL, 'Illegal IP Fragment' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 198, NULL, NULL, 'Illegal or Unauthorized Request Content Type' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 199, NULL, NULL, 'Illegal Parameter Encoding' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 200, NULL, NULL, 'Illegal Request' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 201, NULL, NULL, 'Illegal Response Code' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 202, NULL, NULL, 'Illegal Source IP Address' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 203, NULL, NULL, 'Illegal TCP Option' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 204, NULL, NULL, 'Illegal URL Path Encoding' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 205, NULL, NULL, 'Invalid IP Flags' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 206, NULL, NULL, 'IP Monitor' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 207, NULL, NULL, 'IP Block' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 208, NULL, NULL, 'IP Packet Micro Fragment' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 209, NULL, NULL, 'Malformed HTTP Header Line' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 210, NULL, NULL, 'Malformed URL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 211, NULL, NULL, 'Malformed XML/SOAP Message' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 212, NULL, NULL, 'Malicious Encodings' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 213, NULL, NULL, 'Mid Session Excessive Failed Login attempts to the DB' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 214, NULL, NULL, 'Modified TCP Retransmission Data' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 215, NULL, NULL, 'Multiple Appearances of a Cookie' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 216, NULL, NULL, 'Non-SOAP Access to a SOAP Only URL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 217, NULL, NULL, 'Non Compliant Packet' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 218, NULL, NULL, 'NULL Character in Header Line' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 219, NULL, NULL, 'NULL Character in Header Name' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 220, NULL, NULL, 'NULL Character in Method' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 221, NULL, NULL, 'NULL Character in Parameter Name' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 222, NULL, NULL, 'NULL Character in Parameter Value' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 223, NULL, NULL, 'NULL Character in Query String' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 224, NULL, NULL, 'NULL Character in Request Content' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 225, NULL, NULL, 'NULL Character in URL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 226, NULL, NULL, 'Parameter Length Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 227, NULL, NULL, 'Parameter Read Only Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 228, NULL, NULL, 'Parameter Tampering' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 229, NULL, NULL, 'Parameter Type Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 230, NULL, NULL, 'Parameter Unknown' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 231, NULL, NULL, 'Parameter Value Length Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 232, NULL, NULL, 'Redundant HTTP Headers' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 233, NULL, NULL, 'Redundant UTF-8 Encoding' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 234, NULL, NULL, 'Request Method Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 235, NULL, NULL, 'Required Parameter Not Found' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 236, NULL, NULL, 'Required XML Element Not Found' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 237, NULL, NULL, 'Response Code Distribution for a Single Session Exceeds Limit' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 238, NULL, NULL, 'Response Code Distribution for a Single Source IP Exceeds Limit' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 239, NULL, NULL, 'Response Code Distribution in the System Exceeds Limit' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 240, NULL, NULL, 'Reuse of Expired Session Cookie' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 241, NULL, NULL, 'Server Takeover' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 242, NULL, NULL, 'Session Block' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 243, NULL, NULL, 'Session Hijacking' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 244, NULL, NULL, 'Signature Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 245, NULL, NULL, 'Site Scanning' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 246, NULL, NULL, 'Small TTL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 247, NULL, NULL, 'SOAP Access to a Non-SOAP URL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 248, NULL, NULL, 'Source Code Disclosure' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 249, NULL, NULL, 'SQL Event is Missing a User Name' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 250, NULL, NULL, 'SQL Event Too Long' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 251, NULL, NULL, 'SQL Injection' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 252, NULL, NULL, 'SQL Processor Parse Error' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 253, NULL, NULL, 'SQL Protocol - Invalid Flags' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 254, NULL, NULL, 'SQL Protocol - Invalid Header' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 255, NULL, NULL, 'SQL Protocol - Invalid Header Size' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 256, NULL, NULL, 'SQL Protocol - Invalid Login' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 257, NULL, NULL, 'SQL Protocol - Invalid Parameter Length' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 258, NULL, NULL, 'SQL Protocol - Invalid Statement' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 259, NULL, NULL, 'SQL Protocol - Unauthorized Operation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 260, NULL, NULL, 'SQL Query Executed by an Unauthorized User' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 261, NULL, NULL, 'SQL Query Executed from Unauthorized IP Address' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 262, NULL, NULL, 'SSL Untraceable Connection' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 263, NULL, NULL, 'Stealth Commanding' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 264, NULL, NULL, 'Suspected ICMP LAND Attack' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 265, NULL, NULL, 'Suspected TCP LAND Attack' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 266, NULL, NULL, 'TCP Bad Option Length' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 267, NULL, NULL, 'TCP Bad Option Padding' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 268, NULL, NULL, 'TCP Non Zero Reserved Flags.htm' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 269, NULL, NULL, 'TCP Packet - Micro Fragment' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 270, NULL, NULL, 'TCP Packet that includes SYN with Data' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 271, NULL, NULL, 'TCP Packet that includes SYN with FIN' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 272, NULL, NULL, 'TCP Packet that includes SYN with RST' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 273, NULL, NULL, 'TCP Packet with Bad State' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 274, NULL, NULL, 'TCP SYN with Non Zero ACK Sequence' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 275, NULL, NULL, 'TCP Unexpected SYN' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 276, NULL, NULL, 'Time of Day Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 277, NULL, NULL, 'Too Many Cookies in Request' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 278, NULL, NULL, 'Too Many Headers per Request' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 279, NULL, NULL, 'Too Many of the Same Response Code' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 280, NULL, NULL, 'Too Many IP Sources for a Single Session' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 281, NULL, NULL, 'Too Many Mergers for a Single Session' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 282, NULL, NULL, 'Too Many URL Parameters' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 283, NULL, NULL, 'Too_Many_Headers_per_Response' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 284, NULL, NULL, 'UDP Micro-Fragment' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 285, NULL, NULL, 'Unauthorized Access to Service' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 286, NULL, NULL, 'Unauthorized Database Schema' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 287, NULL, NULL, 'Unauthorized Database User' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 288, NULL, NULL, 'Unauthorized Method for Known URL' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 289, NULL, NULL, 'Unauthorized Query' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 290, NULL, NULL, 'Unauthorized Query Group' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 291, NULL, NULL, 'Unauthorized Sensitive Query' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 292, NULL, NULL, 'Unauthorized Sensitive Query Group' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 293, NULL, NULL, 'Unauthorized Sensitive Table' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 294, NULL, NULL, 'Unauthorized SOAP Action' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 295, NULL, NULL, 'Unauthorized Source Application' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 296, NULL, NULL, 'Unauthorized URL Access' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 297, NULL, NULL, 'Unknown HTTP Request' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 298, NULL, NULL, 'Unknown HTTP Request Method' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 299, NULL, NULL, 'Unknown IP Option' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 300, NULL, NULL, 'Unknown SQL Request' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 301, NULL, NULL, 'Unknown TCP Option' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 302, NULL, NULL, 'Unknown XML Element' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 303, NULL, NULL, 'Untraceable Database User' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 304, NULL, NULL, 'URL is Above Root Directory' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 305, NULL, NULL, 'URL Occurrence for a Single Session Exceeds Limit' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 306, NULL, NULL, 'URL Occurrence for a Single Source IP Address Exceeds Limit' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 307, NULL, NULL, 'URL Occurrence in the System Exceeds Limit' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 308, NULL, NULL, 'Web Worm' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 309, NULL, NULL, 'XML Element Value Length Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 310, NULL, NULL, 'XML Element Value Type Violation' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 311, NULL, NULL, 'Distributed Illegal Byte Code Character in Header Name' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 312, NULL, NULL, 'Distributed Unknown HTTP Request Method' , 0, 1);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1679, 313, NULL, NULL, 'Distributed Illegal Byte Code Character in Method' , 0, 1);